config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :users, only: [:new, :create, :show] do
    resources :favorite_gifs, only: [:create, :destroy, :index]
  end

  resources :categories do
    resources :gifs
  end

  resources :gifs, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gifs, dependent: :destroy

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :category
  validates :category, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites
  has_many :favorite_gifs, through: :favorites, source: :favorited, source_type: 'Gif'
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :all_categories

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    render file: "/public/404" unless current_user && current_admin?
  end

  def current_admin?
    if current_user.role == 1
      true
    else
      false
    end
  end

  def all_categories
    categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize!, except: [:show, :index]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to categories_path
      else
        render :new
      end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = "#{@category.title} was successfully deleted!"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/favorite_gifs_controller.rb
class FavoriteGifsController < ApplicationController
  before_action :set_gif, only: [:create, :destroy]

  def index
    current_user.favorite_gifs
  end

  def create
     if Favorite.create(favorited: @gif, user: current_user)
       redirect_to :back, notice: 'Gif has been favorited'
     else
       redirect_to :back, alert: 'Something went wrong...*sad panda*'
     end
  end

  def destroy
    Favorite.where(favorited_id: @gif.id, user_id: current_user.id).first.destroy
    redirect_to :back, notice: 'Gif is no longer in favorites'
  end

   private

   def set_gif
     @gif = Gif.find(params[:gif_id] || params[:id])
   end
 end
#   def index
#     # @user = current_user
#     @gifs = current_user.favorite_gifs
#     # byebug
#   end
#
#   def show
#   end
#
#   def update
#     # @user = current_user
#     @favorite_gifs = current_user.favorite_gifs
#     @favorite_gifs.update(favorite_gifs_params)
#     if @favorite_gifs.save
#       flash[:success] = "Favorites updated!"
#       redirect_to category_gif_path
#     else
#       redirect_to :back
#     end
#   end
#
#   private
#
#   def favorite_gifs_params
#     params.require(:favorite_gifs).permit(:gif_id, :user_id, :type)
#   end
# end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  require 'json'
  require 'faraday'
  before_action :authorize!, except: [:show, :index]

  def index
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @gifs = @category.gifs
    elsif params[:category]
      @gifs = Gif.where("gif.category.title = ?", params[:category_id])
    else
      @gifs = Gif.all
    end
  end

  def new
    @categories = Category.all.order(:title)
    @gif = Gif.new
  end

  def create
      category = Category.find(params[:category][:category_id])
      query = params[:search]
        response = Faraday.get("http://api.giphy.com/v1/gifs/search?q=#{query}&api_key=dc6zaTOxFJmzC")
        body = response.body
        parsed = JSON.parse(body, :symbolize_names => true)
        img_url = parsed[:data].sample[:images][:original].fetch(:url)

        @gif = category.gifs.create(image_path: img_url)
        flash[:success] = "Gif created successfully"
        redirect_to gifs_path
  end

  def show
    @gif = Gif.find(params[:id])
  end

  private

  def gif_params
    params.require(:gif).permit(:image_path, :category_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged In Successfully"
      redirect_to user_path( current_user )
    else
      flash[:notice] = "Wrong username and/or password"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Logged Out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome #{@user.username}"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each do |category| %>
<%= link_to "#{category.title}", category_gifs_path(category) %><br />
<%= button_to "Delete Category", category_path(category), method: :delete %><br />
<%= button_to "Create a Gif", new_category_gif_path(category), method: :get %><br />
<% end %>

<%= link_to "Create a Category", new_category_path %>

app/views/categories/new.html.erb
<h1>Create a New Category</h1>
<%= form_for @category do |f| %>
<%= f.label :title  %>
<%= f.text_field :title  %>
<%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

app/views/favorite_gifs/index.html.erb
<h1><%= current_user.username %>'s Favorites</h1>

<div class="row">
  <% current_user.favorite_gifs.each do |gif| %>
<div class="col s6 push-s1">
  <img src="<%= gif.image_path %>">
  <%= button_to 'Remove from favorites', user_favorite_gif_path(current_user, gif), method: :delete %>
</div>
  <% end %><br>
</div>

  <%#= link_to "All Gifs", gifs_path %>

app/views/favorite_gifs/show.html.erb
<h1>show page</h1>

app/views/gifs/index.html.erb
<div class="col s12 m4 l2">
  <h1>Gifs Index</h1>
</div>

 <div class="row">
   <% @gifs.each do |gif| %>
   <div class="col s6 push-s1">
        <img src="<%= gif.image_path %>">

        <%- unless current_user.favorite_gifs.exists?(id: gif.id) -%>
          <%= button_to 'Add to favorites', user_favorite_gifs_path(current_user, gif_id: gif), method: :post %>
        <%- else -%>
          <%= button_to 'Remove from favorites', user_favorite_gif_path(current_user, gif), method: :delete %>
        <%- end -%>
    </div>
  <% end %>
 </div>

<%= link_to 'My Favorites', user_favorite_gifs_path(current_user) %><br /><br />
<%= link_to 'Create a Gif', new_gif_path %>

app/views/gifs/new.html.erb
<body>

<h1>Create a Gif</h1>
<%= link_to "Create a Category", new_category_path %><br /><br />
<%= form_tag(gifs_path) do %>
<%= label_tag :category %>
<!-- <select class="browser-default"> -->
<%= collection_select(:category, :category_id, @categories, :id, :title) %>
<!-- </select> -->
<%= label_tag :search %>
<%= text_field_tag :search %>
<%= submit_tag "Generate Gif" %>
<% end %>

<div class="input-field col s12">
    <select>
      <option value="" disabled selected>Choose your option</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Materialize Select</label>
  </div>
<!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
  <script>
     $(document).ready(function() {
        $('select').material_select();
    });
  </script>

</body>

app/views/gifs/show.html.erb
<h1><%= @gif.category.title %> <%= @gif.id %></h1>

<a href="category_gif_path(@gif)">
<img src="<%= @gif.image_path %>">
</a>
<% if current_user %>
  <%= button_to "Add to Favorites",   user_favorite_gif_path(@gif, type: "favorite"), method: :put %>
  <%= button_to "Remove from Favorites", user_favorite_gif_path(@gif, type: "unfavorite"), method: :put %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiphyGen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "flash_#{type}" %>
    <% end %>

<!-- Navbar -->
    <!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <% all_categories.each do |category| %>
  <li><%=link_to category.title, category_gifs_path(category) %></li>
  <% end %>
</ul>
<nav>
  <div class="nav-wrapper lime accent-2 blue-text">
    <a class="brand-logo"><%= link_to "Gifs", gifs_path %></a>
    <ul class="right hide-on-med-and-down">
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" data-activates="dropdown1">Categories<i class="material-icons right"></i></a></li>

    <%- unless current_user == nil -%>
      <li><%= link_to "My Favorites", user_favorite_gifs_path(current_user) %></li>
      <li><%= link_to "Log out", logout_path, method: :delete %> </li>
    <%- else -%>
      <li><%= link_to "Log in", login_path, method: :get %> </li>
    <%- end -%>
    </ul>
  </div>

</nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.password_field :password_confirmation, placeholder: "Confirmation" %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1 class="greeting">Welcome <%= @user.username %></h1>

<%#= link_to "My Favorites", user_favorite_ %>

<div class="favorites">
  <%= button_to "My Favorites", user_favorite_gifs_path(current_user), method: :get %>
</div>
<%= button_to "Logout", logout_path, method: :delete %>